// <auto-generated />
using System;
using LancamentoContabil.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace LancamentoContabil.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LancamentoContabil.Model.ContasContabeis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContaContabil")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(15)");

                    b.Property<string>("Historico")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<int>("LancamentoContabilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoLancamento")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(19,2)");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoContabilId");

                    b.ToTable("ContasContabeis", (string)null);
                });

            modelBuilder.Entity("LancamentoContabil.Model.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodEmpresa")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(3)");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("DATE");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(6)");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(6)");

                    b.HasKey("Id");

                    b.ToTable("Lancamento", (string)null);
                });

            modelBuilder.Entity("LancamentoContabil.Model.ContasContabeis", b =>
                {
                    b.HasOne("LancamentoContabil.Model.Lancamento", "LancamentoContabil")
                        .WithMany("ContasContabeis")
                        .HasForeignKey("LancamentoContabilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LancamentoContabil");
                });

            modelBuilder.Entity("LancamentoContabil.Model.Lancamento", b =>
                {
                    b.Navigation("ContasContabeis");
                });
#pragma warning restore 612, 618
        }
    }
}
